// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorebookAV.Models;

public partial class Class
{
    public int ClassId { get; set; }

    public string Description { get; set; }

    public int? Year { get; set; }

    public virtual ICollection<ClassEvaluation> ClassEvaluations { get; set; } = new List<ClassEvaluation>();

    public virtual ICollection<ClassStudent> ClassStudents { get; set; } = new List<ClassStudent>();
}