// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorebookAV.Models;

public partial class ClassEvaluation
{
    public int ClassEvaluationId { get; set; }

    public int EvaluationTypeId { get; set; }

    public int? StartDateTime { get; set; }

    public int? EndDateTime { get; set; }

    public int? ClassId { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<ClassStudentEvaluation> ClassStudentEvaluations { get; set; } = new List<ClassStudentEvaluation>();

    public virtual PEvaluationType EvaluationType { get; set; }
}