// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorebookAV.Models;

public partial class CurriculumObjective
{
    public string CurriculumObjectiveId { get; set; }

    public string Description { get; set; }
}