// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorebookAV.Models;

public partial class PEvaluationType
{
    public int EvaluationTypeId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ClassEvaluation> ClassEvaluations { get; set; } = new List<ClassEvaluation>();

    public virtual ICollection<ClassStudentEvaluation> ClassStudentEvaluations { get; set; } = new List<ClassStudentEvaluation>();

    public virtual ICollection<PEvaluationTypeParam> PEvaluationTypeParams { get; set; } = new List<PEvaluationTypeParam>();
}