// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScorebookAV.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public long? BirthDay { get; set; }

    public string Gender { get; set; }

    public virtual ICollection<ClassStudentEvaluation> ClassStudentEvaluations { get; set; } = new List<ClassStudentEvaluation>();

    public virtual ICollection<ClassStudent> ClassStudents { get; set; } = new List<ClassStudent>();
}